services:
  issues-bot-v1:
    build:
      context: ../issues-bot
    restart: no
    environment:
      - DISCORD_BOT_TOKEN=${ISSUESV1_DISCORD_BOT_TOKEN}
      - DISCORD_REMOVE_COMMANDS=${ISSUESV1_DISCORD_REMOVE_COMMANDS}
      - DISCORD_GUILD_ID=${ISSUESV1_DISCORD_GUILD_ID}
    volumes:
      - ../issues-bot/.data:/build/.data
    profiles: ["issues-v1-too"]

  issues-bot-v2:
    build:
      context: ../issues-bot-2
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${ISSUESV2_DISCORD_BOT_TOKEN}
      - DISCORD_ENVIRONMENT=prod
    volumes:
      - issuesv2_volume:/build/.data
volumes:
  issuesv2_volume:
